#!/bin/bash

# This script will generate the commands to run the analyses for the
# Atropos paper.
#
# For each error profile, we run Atropos, SeqPurge, and Skewer using
# equivalent (or as similar as possible) arguments. The tests are run
# both locally (Late 2013 Mac Pro, 3.7 GHz quad-core Xeon E5, 32 GB
# memory) and on a cluster (SL6, ???, connected to Isilon NAS over
# InfiniBand??). Atropos is run both with and without a separate Writer
# process. The tests are run on 1) simulated data (see simulate_reads.sh)
# and 2) real data (from the SeqPurge paper, Sturm et al. 2016,
# ftp://ftp.sra.ebi.ac.uk/vol1/ERA494/ERA494451/).
#
# Call: run_analyses.sh -t <threads> -r <root dir>

# A POSIX variable; reset in case getopts has been used
# previously in the shell.
OPTIND=1

# Set default values
mode="local"
threads=8
script_dir=`pwd`
root=`dirname $script_dir`

while getopts "t:r:" opt; do
    case "$opt" in
    t)
        threads=$OPTARG
        ;;
    r)
        root=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

commands="commands_t$threads.sh"

echo "#!/bin/bash" >> $commands
echo "# Generated by prepare_analyses.sh with arguments" \
     "threads: $threads, command file: $commands, root: $root" \
     "unused args: $@" >> $commands
echo "for prog in atropos seqpurge skewer ; do mkdir -p \$prog ; done" >> $commands

## Constants

# binaries
ATROPOS=atropos
SEQPURGE=$root/software/bin/SeqPurge
SKEWER=$root/software/bin/skewer
# adapter sequences
ADAPTER1="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG"
ADAPTER2="AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"
# minimum read length after trimming
MIN_LEN=25
# minimum number of adapter bases that must overlap
MIN_OVERLAP=7
# number of reads to process in a batch
# (also used as prefetch size for SeqPurge)
BATCH_SIZE=5000

## simulated reads

for err in 001 005 01 real
do
  if [ "$err" == "real" ]
  then
      fq1=$root/data/real/NA12878_03_AACGTGAT_L001_R1_001.fastq.gz
      fq2=$root/data/real/NA12878_03_AACGTGAT_L001_R2_001.fastq.gz
  else
      fq1=$root/data/simulated/sim_${err}.1.fq
      fq2=$root/data/simulated/sim_${err}.2.fq
  fi
  
  for qcut in 0 20
  do
    profile="${err}_q${qcut}_writercomp"
    echo "echo Atropos $profile" >> $commands
    echo "/usr/bin/time -p $ATROPOS -T $threads" \
    "-a $ADAPTER1 -A $ADAPTER2" \
    "-O $MIN_OVERLAP -q $qcut --trim-n" \
    "-m $MIN_LEN --batch-size $BATCH_SIZE " \
    "--report-file atropos/${profile}_writer.report.txt" \
    "-o atropos/${profile}.1.fq.gz" \
    "-p atropos/${profile}.2.fq.gz" \
    "--log-level ERROR --quiet" \
    "--compression writer $fq1 $fq2" >> $commands
  
    profile="${err}_q${qcut}_workercomp"
    echo "#echo Atropos $profile" >> $commands
    echo "#/usr/bin/time -p $ATROPOS -T $threads" \
    "-a $ADAPTER1 -A $ADAPTER2" \
    "-O $MIN_OVERLAP -q $qcut --trim-n" \
    "-m $MIN_LEN --batch-size $BATCH_SIZE " \
    "--report-file atropos/${profile}_nowriter.report.txt" \
    "-o atropos/${profile}.1.fq.gz" \
    "-p atropos/${profile}.2.fq.gz" \
    "--log-level ERROR --quiet" \
    "--compression worker $fq1 $fq2" >> $commands
    
    profile="${err}_q${qcut}_nowriter"
    echo "echo Atropos $profile" >> $commands
    echo "/usr/bin/time -p $ATROPOS -T $threads" \
    "-a $ADAPTER1 -A $ADAPTER2" \
    "-O $MIN_OVERLAP -q $qcut --trim-n" \
    "-m $MIN_LEN --batch-size $BATCH_SIZE " \
    "--report-file atropos/${profile}_nowriter.report.txt" \
    "-o atropos/${profile}.1.fq.gz" \
    "-p atropos/${profile}.2.fq.gz" \
    "--log-level ERROR --quiet" \
    "--no-writer-process $fq1 $fq2" >> $commands
    
    profile="${err}_q${qcut}"
    
    # SeqPurge:
    # 1. There is a -mep parameter that may be important
    # for tuning performance; however, the use of this parameter
    # is unclear from the command-line help, and no other guidance
    # is provided. Thus, we leave this parameter set to its
    # default value.
    # 2. We set -match_perc to 0.9 to (presumably) match the
    # default settings in skewer and atropos of max 10% error rate.
    # 3. SeqPurge does not have an option to specifiy minimum
    # overlap size.
    if [ "$qcut" -eq "0" ]
    then
      n=''
      ncut=0
    else
      n='-n'
      ncut=7
    fi
    
    echo "echo SeqPurge $profile" >> $commands
    echo "/usr/bin/time -p $SEQPURGE -in1 $fq1 -in2 $fq2" \
    "-out1 seqpurge/${profile}.1.fq.gz" \
    "-out2 seqpurge/${profile}.2.fq.gz" \
    "-a1 $ADAPTER1 -a2 $ADAPTER2 -threads $threads" \
    "-qcut $qcut -ncut $ncut -min_len $MIN_LEN" \
    "-prefetch $BATCH_SIZE -match_perc 0.9" \
    "-summary seqpurge/${profile}.summary" >> $commands
    
    echo "echo Skewer $profile" >> $commands
    echo "/usr/bin/time -p $SKEWER -m pe -l $MIN_LEN -k $MIN_OVERLAP" \
    "-o skewer/${profile} -z --quiet" \
    "-x $ADAPTER1 -y $ADAPTER2 -t $threads" \
    "-q $qcut $n $fq1 $fq2 > skewer/${profile}.summary.txt" >> $commands
  done
done

chmod +x $commands
