samtools sort -n -O bam -@ 16 -o results/untrimmed.sorted.bam results/untrimmed.bam
samtools sort -n -O bam -@ 16 -o results/atropos_16_real_q0_adapter_workercomp.sorted.bam results/atropos_16_real_q0_adapter_workercomp.bam
samtools sort -n -O bam -@ 16 -o results/atropos_16_real_q0_insert_workercomp.sorted.bam results/atropos_16_real_q0_insert_workercomp.bam
samtools sort -n -O bam -@ 16 -o results/seqpurge_16_real_q0.sorted.bam results/seqpurge_16_real_q0.bam
samtools sort -n -O bam -@ 16 -o results/skewer_16_real_q0.sorted.bam results/skewer_16_real_q0.bam
samtools sort -n -O bam -@ 16 -o results/untrimmed.sorted.bam results/untrimmed.bam
samtools sort -n -O bam -@ 16 -o results/atropos_16_real_q20_adapter_workercomp.sorted.bam results/atropos_16_real_q20_adapter_workercomp.bam
samtools sort -n -O bam -@ 16 -o results/atropos_16_real_q20_insert_workercomp.sorted.bam results/atropos_16_real_q20_insert_workercomp.bam
samtools sort -n -O bam -@ 16 -o results/seqpurge_16_real_q20.sorted.bam results/seqpurge_16_real_q20.bam
samtools sort -n -O bam -@ 16 -o results/skewer_16_real_q20.sorted.bam results/skewer_16_real_q20.bam
