#################################################################
# Data:             Simulated reads for Atropos paper
# Provides:         /data/simulated/sim_{001,005,01}.{1,2}.{aln,fq}
# Base Image:       busybox
#################################################################
FROM busybox
RUN mkdir -p /data/simulated
ADD sim* /data/simulated/
