#################################################################
# Dockerfile
#
# Software:         python
# Software Version: 3.6
# Description:      Python 3.6 with bash
# Website:          https://hub.docker.com/_/python/
# Provides:         python
# Base Image:       alpine
# Build Cmd:        docker build -f Dockerfile -t jdidion/python_bash .
# Pull Cmd:         docker pull jdidion/python_bash
# Run Cmd:          docker run --rm jdidion/python_bash python -h
#################################################################
FROM python:alpine
RUN apk --no-cache add bash